POST http://localhost:3000/customers/add
Content-Type: application/json

 {    "firstName":"hawa",
   "lastName":"mohamed",
    "emailAddress":"pnyambura1mkk0@gmail.com",
    "phoneNumber":"072751165516",
    "dob":"3/4/1913"
     }

### 

GET http://localhost:3000/customers/list

 
 
###

GET http://localhost:3000/customers/601c3e9cf475dc2b28874f61
 
###
DELETE  http://localhost:3000/customers/601c3e9cf475dc2b28874f61

###
 
PATCH  http://localhost:3000/customers/601c3df9f475dc2b28874f5f
Content-Type: application/json

{
    "lastName":  "Mucheru"
    
}